version: '2'

# most of the configuration based on instruction from:
# https://github.com/nginx-proxy/acme-companion/blob/main/docs/Docker-Compose.md
# and
# https://hub.docker.com/r/nginxproxy/acme-companion#:~:text=and%20443.-,Basic%20usage,-(with%20the%20nginx

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.3.1-alpine
    container_name: nginx-proxy
    environment:
      TRUST_DOWNSTREAM_PROXY: "false"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    networks:
      - nginx-proxy

  acme-companion:
    # for SSL certificates generation
    image: nginxproxy/acme-companion:2.2.8
    container_name: nginx-proxy-acme
    environment:
      DEFAULT_EMAIL: letsencrypt@frsource.org
      ACME_EMAIL: kkkubas@o2.pl
      ACME_CA_URI: https://acme.zerossl.com/v2/DV90
      ZEROSSL_API_KEY: ${ZEROSSL_API_KEY}
      ACME_EAB_KID: ${ACME_EAB_KID}
      ACME_EAB_HMAC_KEY: ${ACME_EAB_HMAC_KEY}
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - nginx-proxy

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  nginx-proxy:
    driver: bridge
    name: nginx-proxy
